### ISSUE TITLE
Resetting Widget

### ISSUE THREAD

**Issue by vifi42** [christianwgd/django-friendly-captcha#3]
I have my widget set to data-start = 'auto'. After ValidationError in the form, the form gets reloaded, but the widget doesn't restart.
The documentation of friendlycaptcha gives a reset() function to reset the widget, but I can't seem to find an equivalent for this.

**Comment by christianwgd** [comment]
Oh, sorry, didn't need that by now and not sure, that these existed, when i created the library. I will add the custom widgets for the FrcCaptchaField and make a new release.

Thanks for reporting...

**Comment by vifi42** [comment]
Thanks so much!
I narrowed it down to the fact that I'm using htmx and hx-post with my forms and this seemed to not trigger a reset automatically. I for now worked around the problem by switching to "normal" POST methods.

**Comment by christianwgd** [comment]
Just released 0.1.2 on pypi.org. If you add the data-start attr in the FrcCaptchaField like this

`captcha = FrcCaptchaField(widget=FrcCaptchaWidget(attrs={'data-start': 'auto'}))`

it will render this parameter to the html field

`<div captcha_sitekey="" class="frc-captcha" data-lang="de" data-start="auto" id="id_captcha" title="" required="" data-attached="1"><div class="frc-container">`

**Comment by vifi42** [comment]
Thanks for the quick update. Several problems occurred after upgrading though.

1. The data-start-attribute doesn't make into the final html and subsequently doesn't automatically start the captcha. For me at least it outputs this:
`<div captcha_sitekey="<mysitekey>" class="frc-captcha" data-lang="de" id="id_captcha" required="" data-attached="1"><div class="frc-container">`
2. For some reason this also leads to a "sitekey not set" error - although it is obviously there.

I think you missed the point I was trying to make in the first place though. I managed to set the data-start attribute by creating my own html template for the widget - the update makes this a lot cleaner though - so thanks! But I was actually searching for a way to manually reset the widget with this: (this is from widget API documentation from the friendlycaptcha homepage)

> If you are building a single page application (SPA), chances are the page will not refresh after the captcha is submitted. As a solved captcha can only be used once, you will have to reset the widget yourself (e.g. on submission). You can call the reset() function on the widget instance to achieve this.
>For example, if you are using the automatically created widget:
>friendlyChallenge.autoWidget.reset();

I'm new to web-development and startet this Django-Project so you'll have to excuse me if these questions seem a little dumb. Optimally I would call something like the above line (in python obviously and not in js) in a view before rendering it. The Captcha not resetting happens only after the form comes back as not valid. If I reload normally it works just fine.

**Comment by christianwgd** [comment]
Since i didn't want to parse the optional attrs in the template, i removed the template (and because it is quite trivial). As you can see in my comment above, the custom attrs are rendered correctly in the HTML. 
Since your HTML lacks the "sitekey" attr, i suppose your code still uses your own template. Could you try to remove that?

**Comment by christianwgd** [comment]
Ok, i tried again and saw the same error "sitekey not set". Let me get into that...

**Comment by christianwgd** [comment]
I had published 0.1.3 on pypi. Can you please try, it should work now. 

Sometimes working too fast is producing these kind of errors. Sorry for any inconvenience...
