### ISSUE TITLE
solution_missing

### ISSUE THREAD

**Issue by membranobruno** [christianwgd/django-friendly-captcha#4]
Hi. The values is generated on html form. 

But  doesn't send to server on submit. 
Each time I got the error 

Captcha failed validation {'success': False, 'errors': ['solution_missing']}

Tnanks a lot for any help

**Comment by christianwgd** [comment]
Hi, I checked and found that in the latest fix a line in the Catpcha Widget got lost. Ich try to create a new release tomorrow...

**Comment by membranobruno** [comment]
Perfect! Everything works.

**Comment by christianwgd** [comment]
You're welcome! Thanks for the hint, otherwise I wouldn't have noticed.
